checks:
  php: true

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - command: XDEBUG_MODE=coverage vendor/bin/phpunit --configuration=phpunit.xml
            coverage:
              file: var/tests-coverage.xml
              format: clover
      environment:
        php:
          # https://php-package-mirror.scrutinizer-ci.com/8.4.11.tar.bz2
          version: 8.4.11
          pecl_extensions:
            - xdebug
            - imap
  dependencies:
    before:
      - composer install --no-progress --prefer-dist

tools:
  php_code_sniffer:
    enabled: true
    config:
      standard: PSR12

filter:
  paths:
    - src/*
  excluded_paths:
    - resources/*
    - tests/*
    - tools/*
    - vendor/*
